# Generated by Django 2.2.16 on 2020-11-14 16:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_auto_20201113_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 16, 16, 41, 23, 77653, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
