# Generated by Django 2.2.16 on 2020-11-14 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_auto_20201114_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 16, 17, 26, 14, 201894, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
