# Generated by Django 2.2.16 on 2020-11-30 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0009_auto_20201114_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 12, 8, 11, 815268, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
